/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/Criar`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/Login`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/avisos/avisos` | `/avisos/avisos`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/configurações/Perfil` | `/configurações/Perfil`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/dashboard/Account` | `/dashboard/Account`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/dashboard/Visualizações` | `/dashboard/Visualizações`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/vagas/CLT` | `/vagas/CLT`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/vagas/Freelancer` | `/vagas/Freelancer`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/vagas/VagasEmprego` | `/vagas/VagasEmprego`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/Criar`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/Login`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/avisos/avisos` | `/avisos/avisos`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/configurações/Perfil` | `/configurações/Perfil`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/dashboard/Account` | `/dashboard/Account`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/dashboard` | `/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/dashboard/Visualizações` | `/dashboard/Visualizações`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/vagas/CLT` | `/vagas/CLT`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/vagas/Freelancer` | `/vagas/Freelancer`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/vagas/VagasEmprego` | `/vagas/VagasEmprego`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/Criar${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/Login${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/avisos/avisos${`?${string}` | `#${string}` | ''}` | `/avisos/avisos${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/configurações/Perfil${`?${string}` | `#${string}` | ''}` | `/configurações/Perfil${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/dashboard/Account${`?${string}` | `#${string}` | ''}` | `/dashboard/Account${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/dashboard${`?${string}` | `#${string}` | ''}` | `/dashboard${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/dashboard/Visualizações${`?${string}` | `#${string}` | ''}` | `/dashboard/Visualizações${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/vagas/CLT${`?${string}` | `#${string}` | ''}` | `/vagas/CLT${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/vagas/Freelancer${`?${string}` | `#${string}` | ''}` | `/vagas/Freelancer${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/vagas/VagasEmprego${`?${string}` | `#${string}` | ''}` | `/vagas/VagasEmprego${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/Criar`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/Login`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/avisos/avisos` | `/avisos/avisos`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/configurações/Perfil` | `/configurações/Perfil`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/dashboard/Account` | `/dashboard/Account`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/dashboard/Visualizações` | `/dashboard/Visualizações`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/vagas/CLT` | `/vagas/CLT`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/vagas/Freelancer` | `/vagas/Freelancer`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/vagas/VagasEmprego` | `/vagas/VagasEmprego`; params?: Router.UnknownInputParams; };
    }
  }
}
